apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/scc: restricted
    creationTimestamp: 2018-09-03T19:13:43Z
    generateName: pod-demo-5778b67d-
    labels:
      pod-template-hash: "13346238"
      run: pod-demo
    name: pod-demo-5778b67d-cshrb
    namespace: pod-demo
    ownerReferences:
    - apiVersion: extensions/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: pod-demo-5778b67d
      uid: 794c40ce-afad-11e8-9949-54e1ad4b0979
    resourceVersion: "1815"
    selfLink: /api/v1/namespaces/pod-demo/pods/pod-demo-5778b67d-cshrb
    uid: 794ffeca-afad-11e8-9949-54e1ad4b0979
  spec:
    containers:
    - image: yemax/pod-demo:1
      imagePullPolicy: IfNotPresent
      name: pod-demo
      ports:
      - containerPort: 8081
        protocol: TCP
      resources: {}
      securityContext:
        capabilities:
          drop:
          - KILL
          - MKNOD
          - SETGID
          - SETUID
        runAsUser: 1000080000
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-54dv6
        readOnly: true
    dnsPolicy: ClusterFirst
    imagePullSecrets:
    - name: default-dockercfg-gtlpq
    nodeName: localhost
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1000080000
      seLinuxOptions:
        level: s0:c9,c4
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    volumes:
    - name: default-token-54dv6
      secret:
        defaultMode: 420
        secretName: default-token-54dv6
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2018-09-03T19:13:43Z
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: 2018-09-03T19:13:44Z
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: 2018-09-03T19:13:43Z
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://48d7d84d25a81ddc3e4c48649d7f1f5f73810b79ea175d3446729fa967c9ab88
      image: pod-demo:latest
      imageID: docker-pullable://yemax/pod-demo@sha256:dbfb12a1e2b7b9287097f78eeefe44105e44f3b63fcf1161b43d9daeb8fbc908
      lastState: {}
      name: pod-demo
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: 2018-09-03T19:13:44Z
    hostIP: 192.168.31.130
    phase: Running
    podIP: 172.18.0.3
    qosClass: BestEffort
    startTime: 2018-09-03T19:13:43Z
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
