apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: pod-demo
    openshift.io/deployment.name: pod-demo-1
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/scc: restricted
  creationTimestamp: 2018-09-07T17:42:42Z
  generateName: pod-demo-1-
  labels:
    app: pod-demo
    deployment: pod-demo-1
    deploymentconfig: pod-demo
  name: pod-demo-1-zzhkm
  namespace: qa-fest-2018
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: pod-demo-1
    uid: 6b46794b-b2c5-11e8-a920-54e1ad4b0979
  resourceVersion: "1861"
  selfLink: /api/v1/namespaces/qa-fest-2018/pods/pod-demo-1-zzhkm
  uid: 6c0d454f-b2c5-11e8-a920-54e1ad4b0979
spec:
  containers:
  - image: yemax/pod-demo:1
    imagePullPolicy: IfNotPresent
    name: pod-demo
    ports:
    - containerPort: 8081
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000080000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-scgb5
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-dockercfg-58ljs
  nodeName: localhost
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000080000
    seLinuxOptions:
      level: s0:c9,c4
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-scgb5
    secret:
      defaultMode: 420
      secretName: default-token-scgb5
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-09-07T17:42:42Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-09-07T17:42:44Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-09-07T17:42:42Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://bab20214628e42539193197d2d109cb30d61ea6253832fc06e5abb099ca23884
    image: pod-demo:latest
    imageID: docker-pullable://yemax/pod-demo@sha256:dbfb12a1e2b7b9287097f78eeefe44105e44f3b63fcf1161b43d9daeb8fbc908
    lastState: {}
    name: pod-demo
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-09-07T17:42:43Z
  hostIP: 192.168.31.130
  phase: Running
  podIP: 172.18.0.3
  qosClass: BestEffort
  startTime: 2018-09-07T17:42:42Z
