apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    openshift.io/deployer-pod.completed-at: 2018-09-07 17:42:44 +0000 UTC
    openshift.io/deployer-pod.created-at: 2018-09-07 17:42:41 +0000 UTC
    openshift.io/deployer-pod.name: pod-demo-1-deploy
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: pod-demo
    openshift.io/deployment.phase: Complete
    openshift.io/deployment.replicas: "1"
    openshift.io/deployment.status-reason: config change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"pod-demo","namespace":"qa-fest-2018","selfLink":"/apis/apps.openshift.io/v1/namespaces/qa-fest-2018/deploymentconfigs/pod-demo","uid":"6b44cd41-b2c5-11e8-a920-54e1ad4b0979","resourceVersion":"1823","generation":1,"creationTimestamp":"2018-09-07T17:42:41Z","labels":{"app":"pod-demo"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"}],"replicas":1,"revisionHistoryLimit":10,"test":false,"selector":{"app":"pod-demo","deploymentconfig":"pod-demo"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"pod-demo","deploymentconfig":"pod-demo"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"containers":[{"name":"pod-demo","image":"yemax/pod-demo:1","ports":[{"containerPort":8081,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":0,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]}}}
  creationTimestamp: 2018-09-07T17:42:41Z
  generation: 2
  labels:
    app: pod-demo
    openshift.io/deployment-config.name: pod-demo
  name: pod-demo-1
  namespace: qa-fest-2018
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: pod-demo
    uid: 6b44cd41-b2c5-11e8-a920-54e1ad4b0979
  resourceVersion: "1866"
  selfLink: /api/v1/namespaces/qa-fest-2018/replicationcontrollers/pod-demo-1
  uid: 6b46794b-b2c5-11e8-a920-54e1ad4b0979
spec:
  replicas: 1
  selector:
    app: pod-demo
    deployment: pod-demo-1
    deploymentconfig: pod-demo
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "1"
        openshift.io/deployment-config.name: pod-demo
        openshift.io/deployment.name: pod-demo-1
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: pod-demo
        deployment: pod-demo-1
        deploymentconfig: pod-demo
    spec:
      containers:
      - image: yemax/pod-demo:1
        imagePullPolicy: IfNotPresent
        name: pod-demo
        ports:
        - containerPort: 8081
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
