apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2018-09-07T17:42:41Z
  labels:
    app: pod-demo
  name: pod-demo
  namespace: qa-fest-2018
  resourceVersion: "1826"
  selfLink: /api/v1/namespaces/qa-fest-2018/services/pod-demo
  uid: 6b47f0a4-b2c5-11e8-a920-54e1ad4b0979
spec:
  clusterIP: 172.30.152.124
  ports:
  - name: 8081-tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: pod-demo
    deploymentconfig: pod-demo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
